version: '3.5'

services:
### MariaDB ###
  db:
    image: mariadb:${MARIADB_VERSION}
    container_name: ${PROJECT_NAME}-mariadb
    restart: ${RESTART_MODE}
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    ports:
      - ${MARIADB_PORT}:${MARIADB_PORT}

### NGINX ###    
  webserver:
    container_name: ${PROJECT_NAME}-webserver
    restart: ${RESTART_MODE}
    build:
      context: ./nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    volumes:
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx/config/sites-enabled/:/etc/nginx/conf.d/:ro
      - ./app/:/var/www/html/
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - db
      - php-fpm
      - memcached
      - redis
    ports:
      - ${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}
      - ${NGINX_HTTPS_PORT}:${NGINX_HTTPS_PORT}

### PHP-FPM ###
  php-fpm:
    container_name: ${PROJECT_NAME}-php-fpm
    restart: ${RESTART_MODE}
    build: 
      context: ./php-fpm
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ./app/:/var/www/html/
      - ./php-fpm/config/:/usr/local/etc/php/
    depends_on:
      - db
    ports:
      - ${PHP_FPM_PORT}:${PHP_FPM_PORT}

### Supervisor ###
  supervisor:
    container_name: ${PROJECT_NAME}-supervisor
    restart: ${RESTART_MODE}
    build:
      context: ./supervisor
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ./app/:/var/www/html
      - ./supervisor/conf.d/:/etc/supervisor/conf.d/:ro
      - ./php-fpm/config/:/usr/local/etc/php/:ro
    depends_on:
      - db
      - php-fpm

### Memcached ###
  memcached:
    image: memcached:${MEMCACHED_VERSION}-alpine
    container_name: ${PROJECT_NAME}-db
    restart: ${RESTART_MODE}
    depends_on:
      - db
      - php-fpm
    ports:
      - ${MEMCACHED_PORT}:${MEMCACHED_PORT}

### Redis ###
  redis:  
    image: redis:${REDIS_VERSION}-alpine
    container_name: ${PROJECT_NAME}-redis
    restart: ${RESTART_MODE}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    volumes: 
      - cache:/data
    depends_on:
      - db
      - php-fpm

### Adminer ###
  adminer:
    image: adminer
    container_name: ${PROJECT_NAME}-adminer
    restart: ${RESTART_MODE}
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}
    depends_on:
      - db
      - webserver

volumes:
  db:
  cache:
    driver: local
