version: '3'

services:
### MariaDB ###
  db:
    image: mariadb:10.7
    container_name: ${PROJECT_NAME}-mariadb
    restart: ${RESTART_MODE}
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

### NGINX ###    
  webserver:
    build: ./nginx
    image: nginx:1.22.0
    container_name: ${PROJECT_NAME}-webserver
    restart: ${RESTART_MODE}
    volumes:
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx/config/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/:/var/www/html
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - db
      - php-fpm
    ports:
      - 80:80
      - 443:443

### PHP-FPM ###
  php-fpm:
    container_name: ${PROJECT_NAME}-php-fpm
    build: ./php-fpm
    restart: ${RESTART_MODE}
    volumes:
      - ./app/:/var/www/html
      - ./php-fpm/config/:/usr/local/etc/php/
    depends_on:
      - db
    ports:
      - 9000:9000

### Supervisor ###
  supervisor:
    build:
      context: ./supervisor
    container_name: ${PROJECT_NAME}-supervisor
    restart: ${RESTART_MODE}
    volumes:
      - ./app/:/var/www/html
      - ./supervisor/conf.d/:/etc/supervisor/conf.d/:ro
      - ./php-fpm/config/:/usr/local/etc/php/:ro
    depends_on:
      - db
      - php-fpm

### Memcached ###
  memcached:
    image: memcached:1.6-alpine
    restart: ${RESTART_MODE}
    container_name: ${PROJECT_NAME}-db
    restart: ${RESTART_MODE}
    depends_on:
      - db
      - php-fpm
    ports:
      - 11211:11211

### Redis ###
  redis:  
    image: redis:6.2-alpine
    restart: ${RESTART_MODE}
    container_name: ${PROJECT_NAME}-redis
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    volumes: 
      - cache:/data
    depends_on:
      - db
      - php-fpm

### Adminer ###
  adminer:
    image: adminer
    restart: ${RESTART_MODE}
    container_name: ${PROJECT_NAME}-adminer
    ports:
      - 8080:8080
    depends_on:
      - db
      - webserver

volumes:
  db:
  cache:
    driver: local
